SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS Grimoire_Guardians;
CREATE SCHEMA Grimoire_Guardians;
USE Grimoire_Guardians;

CREATE TABLE Player(
player_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
Username VARCHAR(45) NOT NULL,
Contrasena VARCHAR(45) NOT NULL,
Description VARCHAR(45) NOT NULL,
Is_NPC TINYINT NOT NULL,
Elixir_count SMALLINT UNSIGNED NOT NULL,
Turn_elixir_gain SMALLINT UNSIGNED NOT NULL,
PRIMARY KEY(player_id)

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Card(
card_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
Name VARCHAR(45) NOT NULL,
Description VARCHAR(45) NOT NULL,
HP TINYINT NOT NULL,
AP TINYINT NOT NULL,
Elixir_cost TINYINT NOT NULL,
Type VARCHAR(45) NOT NULL,
Element VARCHAR(45) NOT NULL,
Strength VARCHAR(45) NOT NULL,
Weakness VARCHAR(45) NOT NULL,

PRIMARY KEY(card_id)


)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Deck(
deck_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
Creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
Last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
Name VARCHAR(45) NOT NULL,
Size TINYINT UNSIGNED NOT NULL,

PRIMARY KEY(deck_id)

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*The table reward can be normalized if we separate the reward type into another table*/
CREATE TABLE Reward(
reward_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,

player_id SMALLINT UNSIGNED NOT NULL,

Reward_type VARCHAR(45) NOT NULL,
Reward_quantity SMALLINT UNSIGNED NOT NULL,

PRIMARY KEY(reward_id),

CONSTRAINT fk_Rewards_Payer FOREIGN KEY(player_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Inventory(
inventory_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,

card_id SMALLINT UNSIGNED NOT NULL,
player_id SMALLINT UNSIGNED NOT NULL,
deck_id SMALLINT UNSIGNED NOT NULL,

reward_id SMALLINT UNSIGNED NOT NULL,

PRIMARY KEY(inventory_id),

CONSTRAINT fk_Inventory_Player FOREIGN KEY(player_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Inventory_Card FOREIGN KEY(card_id) REFERENCES Card (card_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Inventory_Deck FOREIGN KEY(deck_id) REFERENCES Deck (deck_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Inventory_Reward FOREIGN KEY(reward_id) REFERENCES Reward (reward_id) ON DELETE RESTRICT ON UPDATE CASCADE


)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Hand(

hand_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,

card_id SMALLINT UNSIGNED NOT NULL,
player_id SMALLINT UNSIGNED NOT NULL,
deck_id SMALLINT UNSIGNED NOT NULL,

Date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY(hand_id),

CONSTRAINT fk_Hand_Player FOREIGN KEY(player_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Hand_Card FOREIGN KEY(card_id) REFERENCES Card (card_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Hand_Deck FOREIGN KEY(deck_id) REFERENCES Deck (deck_id) ON DELETE RESTRICT ON UPDATE CASCADE





)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Level(
level_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,

player1_id SMALLINT UNSIGNED NOT NULL,
player2_id SMALLINT UNSIGNED NOT NULL,
winner_id SMALLINT UNSIGNED NOT NULL,

Date_played TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY(level_id),

CONSTRAINT fk_Level_player1 FOREIGN KEY(player1_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Level_player2 FOREIGN KEY(player2_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Level_winner FOREIGN KEY(winner_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*The word match cant be used to create a table, SQL reads it as a command*/
CREATE TABLE Fight(
fight_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,

hand_id SMALLINT UNSIGNED NOT NULL,
deck_id SMALLINT UNSIGNED NOT NULL,

Elixir_gained TINYINT UNSIGNED NOT NULL,

PRIMARY KEY(fight_id),

CONSTRAINT fk_Fight_Hand FOREIGN KEY(hand_id) REFERENCES Hand (hand_id)ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Fight_Deck FOREIGN KEY(deck_id) REFERENCES Deck (deck_id) ON DELETE RESTRICT ON UPDATE CASCADE

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Turn(
turn_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,

level_id SMALLINT UNSIGNED NOT NULL,
player_id SMALLINT UNSIGNED NOT NULL,
hand_id SMALLINT UNSIGNED NOT NULL,
fight_id SMALLINT UNSIGNED NOT NULL,

Duration SMALLINT UNSIGNED NOT NULL,
Turn_status ENUM('player','NPC'),
Date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY(turn_id),

CONSTRAINT fk_Turn_Level FOREIGN KEY(level_id) REFERENCES Level (level_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Turn_Player FOREIGN KEY(player_id) REFERENCES Player (player_id) ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Turn_Hand FOREIGN KEY(hand_id) REFERENCES Hand (hand_id)ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Turn_Fight FOREIGN KEY(fight_id) REFERENCES Fight (fight_id)ON DELETE RESTRICT ON UPDATE CASCADE


)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Played(

played_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,

turn_id SMALLINT UNSIGNED NOT NULL,
card_id SMALLINT UNSIGNED NOT NULL,

Date_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
AP TINYINT NOT NULL,
HP TINYINT NOT NULL,

PRIMARY KEY(played_id),

CONSTRAINT fk_Played_Turn FOREIGN KEY(turn_id) REFERENCES Turn (turn_id)ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_Played_Card FOREIGN KEY(card_id) REFERENCES Card (card_id) ON DELETE RESTRICT ON UPDATE CASCADE


)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



